aliases:
  - &python_settings
    types: [python]
    files: ./backend
    exclude: >
      (?x)^(
        .+/migrations/.+|
      )$
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
      - <<: *python_settings
        id: isort
        args:
          - --settings-path=./backend/setup.cfg
  - repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
      - <<: *python_settings
        id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - <<: *python_settings
        id: flake8
        args:
          - --config=./backend/setup.cfg
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.790"
    hooks:
      - <<: *python_settings
        id: mypy
        args:
          - --config-file=./backend/setup.cfg
        additional_dependencies: [pydantic==1.7, tortoise-orm==0.16.18]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: detect-private-key
      - <<: *python_settings
        id: debug-statements
      - <<: *python_settings
        id: check-ast
      - <<: *python_settings
        id: check-builtin-literals
