repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
      - id: isort
        types: [python]
        files: ./backend
        exclude: (?x)^(.+/migrations/.+|)$
        args:
          - --settings-path=./backend/setup.cfg
  - repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
      - id: black
        types: [python]
        files: ./backend
        exclude: (?x)^(.+/migrations/.+|)$
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        types: [python]
        files: ./backend
        exclude: (?x)^(.+/migrations/.+|)$
        args:
          - --config=./backend/setup.cfg
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.790"
    hooks:
      - id: mypy
        types: [python]
        files: ./backend
        exclude: (?x)^(.+/migrations/.+|)$
        args:
          - --config-file=./backend/setup.cfg
        additional_dependencies: [pydantic==1.7, tortoise-orm==0.16.18]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: detect-private-key
        types: [python]
        files: ./backend
        exclude: (?x)^(.+/migrations/.+|)$
      - id: debug-statements
        types: [python]
        files: ./backend
        exclude: (?x)^(.+/migrations/.+|)$
      - id: check-ast
        types: [python]
        files: ./backend
        exclude: (?x)^(.+/migrations/.+|)$
      - id: check-builtin-literals
