version: "3.8"

services:
  proxy:
    command:
      - --api.insecure=true
      - --entrypoints.web.address=:80

  frontend:
    command: npm run serve --port=8080
    build:
      target: build-stage
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./frontend
        target: /app/
    stdin_open: true
    tty: true
    environment:
      CHOKIDAR_USEPOLLING: "true"

  api:
    command: ["/start-reload.sh"]
    build:
      args:
        - INSTALL_DEV=true
    environment:
      - DEBUG=True
      - DOMAIN=localhost
    ports:
      - 8000:8000
