services:
  proxy:
    image: traefik:v2.2
    container_name: proxy
    command:
      - --api.insecure=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/lets-encrypt/acme.json
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 443:443
      - 8080:8080 # traefik dashboard
    depends_on:
      - frontend
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN_PROD}`)
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.tls.certresolver=letsencrypt
      # HTTP Redirect
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.redirect-https.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.redirect-https.entrypoints=web
      - traefik.http.routers.redirect-https.middlewares=redirect-to-https

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: prod-stage
    ports:
      - 8888:80
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DOMAIN_DEV
      - DOMAIN_STAG
      - DOMAIN_PROD
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`${DOMAIN_PROD}`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.tls.certresolver=letsencrypt

  backend:
    container_name: backend
    build:
      context: ./backend
      target: prod-stage
    ports:
      - 8000:80
    env_file:
      - .env
    environment:
      - PROJECT_NAME
      - PROJECT_DESCRIPTION
      - DEBUG=${DEBUG-false}
      - SERVER_NAME=${DOMAIN_PROD}
      - SERVER_HOST=https://${DOMAIN_PROD}
      - POSTGRES_HOST=postgres
      - POSTGRES_IMAGE=${POSTGRES_IMAGE}
      - REDIS_URL=redis://redis:6379/0
      - SMTP_TLS
      - SMTP_PORT
      - SMTP_HOST
      - SMTP_USER
      - SMTP_PASSWORD
      - EMAILS_FROM_EMAIL
    depends_on:
      - postgres
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`${DOMAIN_PROD}`) && PathPrefix(`/token`,`/api`,`/ws`,`/docs`,`/redoc`)
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls=true
      - traefik.http.routers.backend.tls.certresolver=letsencrypt

  redis:
    container_name: redis
    image: redis:5-alpine

  postgres:
    container_name: postgres
    image: ${POSTGRES_IMAGE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.${DOMAIN_PROD}`)
      - traefik.http.routers.pgadmin.entrypoints=websecure
      - traefik.http.routers.pgadmin.tls=true
      - traefik.http.routers.pgadmin.tls.certresolver=letsencrypt
      - traefik.http.services.pgadmin.loadbalancer.server.port=5050

volumes:
  postgres_data: null
