x-shared-environment: &shared-environment
# postgres
  POSTGRES_HOST: postgres
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: notsecret
# redis
  REDIS_URL: redis://redis:6379/0

services:
  proxy:
    environment:
      <<: *shared-environment
    command:
      - --api.insecure=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.traefik.address=:8888 # traefik dashboard
      - --providers.file.directory=/etc/traefik/
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=false
    ports:
      - 8888:8888 # traefik dashboard
    labels:
      - traefik.http.middlewares.testheader.headers.isDevelopment=true

  frontend:
    build:
      target: dev-stage

    volumes:
      - .:/srv/app:rw
      - node_modules:/srv/app/frontend/node_modules
    environment:
      <<: *shared-environment
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 1
      VUE_APP_DEV_PROXY_API_HOST: backend:8001
    tty: true
    stdin_open: true

  backend:
    environment:
      <<: *shared-environment
      DEBUG: 1
      SECRET_KEY: notsecret
      ALLOWED_HOSTS: '["*"]'
      BACKEND_CORS_ORIGINS: '["*"]'
    links:
      - postgres
    build:
      target: dev-stage
    ports:
      - 8001 # For e2e testing
    volumes:
      - .:/srv/app:rw
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    environment:
      <<: *shared-environment
      POSTGRES_INITDB_ARGS: "--data-checksums"
    command: ["postgres", "-c", "log_statement=all"]

  redis:
    environment:
      <<: *shared-environment

  pgadmin:
    environment:
      <<: *shared-environment
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: notsecret

volumes:
  node_modules:
