version: "3.8"

services:
  proxy:
    command:
      - --api.insecure=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.traefik.address=:8888
      - --providers.file.directory=/etc/traefik/
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=false
    labels:
      - traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN_DEV}`)

  frontend:
    build:
      target: dev-stage
    ports:
      - 8080
    volumes:
      - .:/app:ro
      - ./.git:/app/.git:rw
      - ./frontend:/app/frontend:rw
    stdin_open: true
    tty: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
    labels:
      - traefik.http.routers.frontend.rule=Host(`${DOMAIN_DEV}`)

  backend:
    build:
      target: dev-stage
    command: /bin/bash -c "uvicorn --reload --host=0.0.0.0 --port=8000 app.main:app"
    volumes:
      - .:/app:ro
      - ./.git:/app/.git:rw
      - ./backend:/app/backend:rw
    environment:
      - DEBUG=true
      - SERVER_NAME=${DOMAIN_DEV}
      - SERVER_HOST=https://${DOMAIN_DEV}
      - PYTHONDONTWRITEBYTECODE=1
    labels:
      - traefik.http.routers.backend.rule=Host(`${DOMAIN_DEV}`) && PathPrefix(`/api`,`/ws`,`/docs`,`/redoc`)

  pgadmin:
    labels:
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.${DOMAIN_DEV}`)
