version: "3.8"

services:
  frontend:
    env_file:
      - .env
    build:
      context: ./frontend
      target: build-stage
    command: npm run serve
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./frontend
        target: /app/
    # stdin_open: true
    # tty: true
    environment:
      ENVIRONMENT: development
      CHOKIDAR_USEPOLLING: "true"
