version: "3.8"

services:
  proxy:
    command:
      - --api.insecure=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.traefik.address=:8888
      - --providers.file.directory=/etc/traefik/
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=false
    volumes:
      - ./selfsigned:/etc/selfsigned/:ro
      - type: bind
        source: ./traefik
        target: /etc/traefik/
    labels:
      - traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN_DEV}`)

  frontend:
    command: npm run serve --port=8080
    build:
      target: build-stage
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app/
    stdin_open: true
    tty: true
    environment:
      CHOKIDAR_USEPOLLING: "true"
    labels:
      - traefik.http.routers.frontend.rule=Host(`${DOMAIN_DEV}`)

  backend:
    command: ["/start-reload.sh"]
    build:
      args:
        - INSTALL_DEV=true
    volumes:
      - ./backend:/app/
    environment:
      - DEBUG=true
      - SERVER_NAME=${DOMAIN_DEV}
      - SERVER_HOST=https://${DOMAIN_DEV}
    labels:
      - traefik.http.routers.backend.rule=Host(`${DOMAIN_DEV}`) && PathPrefix(`/api`,`/ws`,`/docs`,`/redoc`)

  pgadmin:
    labels:
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.${DOMAIN_DEV}`)
