services:
  proxy:
    command:
      - --api.insecure=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.file.directory=/etc/traefik/
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=false
    labels:
      - traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN_DEV}`)
      - traefik.http.middlewares.testheader.headers.isDevelopment=true

  frontend:
    build:
      target: dev-stage
    volumes:
      - .:/srv/app:rw
      - node_modules:/srv/app/frontend/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    labels:
      - traefik.http.routers.frontend.rule=Host(`${DOMAIN_DEV}`)

  backend:
    build:
      target: dev-stage
    volumes:
      - .:/srv/app:rw
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DEBUG=true
      - SERVER_NAME=${DOMAIN_DEV}
      - SERVER_HOST=https://${DOMAIN_DEV}
      - DISPLAY=${DISPLAY}
    labels:
      - traefik.http.routers.backend.rule=Host(`${DOMAIN_DEV}`) && PathPrefix(`/token`,`/api`,`/ws`,`/docs`,`/redoc`)

  pgadmin:
    labels:
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.${DOMAIN_DEV}`)

volumes:
  node_modules:
